# 部署前请修改 baseurl
baseurl = "https://demo.stack.jimmycai.com"
languageCode = "zh-CN"
title = "Ciallo~"

# 主题多语言支持
# 可用值: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "zh-cn"

# 如果 DefaultContentLanguage 是 [zh-cn ja ko]，请将 hasCJKLanguage 设置为 true
# 这样 .Summary 和 .WordCount 在 CJK 语言下才能正确工作
hasCJKLanguage = true

# 使用前请修改为你的 Disqus shortname
#disqusShortname = "hugo-theme-stack"

[pagination]
pagerSize = 5