name: Update theme

# 控制工作流何时运行
on:
  schedule:
    # 每天00:00 UTC自动更新主题
    - cron: "0 0 * * *"
  # 允许从Actions选项卡手动运行此工作流
  workflow_dispatch:

jobs:
  update-theme:
    runs-on: ubuntu-latest

    permissions:
      # 给予默认GITHUB_TOKEN写入权限，以提交和推送添加或更改的文件到仓库
# 添加或更改的文件到仓库。
      contents: write
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 0.123.8
          extended: true

      - name: Update theme
        run: hugo mod get -u github.com/CaiJimmy/hugo-theme-stack/v3

      - name: Tidy go.mod, go.sum
        run: hugo mod tidy

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "CI: Update theme"
